spring:
  jpa:
    properties:
      hibernate.format_sql: true
      javax.persistence.lock.timeout: 10000
logging:
  level:
    ROOT: INFO
    org.springframework.transaction: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
